/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2017-05-25 01:43:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.cal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cal.*;

public final class cal1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("cal");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD><TITLE>\r\n");
      out.write("    Calendar: A JSP APPLICATION\r\n");
      out.write("</TITLE></HEAD>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<BODY BGCOLOR=\"white\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      cal.TableBean table = null;
      synchronized (session) {
        table = (cal.TableBean) _jspx_page_context.getAttribute("table", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (table == null){
          table = new cal.TableBean();
          _jspx_page_context.setAttribute("table", table, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");

    table.processRequest(request);
    if (table.getProcessError() == false) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- html table goes here -->\r\n");
      out.write("<CENTER>\r\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=yellow CELLPADDING=15>\r\n");
      out.write("<TR>\r\n");
      out.write("<TD ALIGN=CENTER> <A HREF=cal1.jsp?date=prev> prev </A>\r\n");
      out.write("<TD ALIGN=CENTER> Calendar:");
      out.print( table.getDate() );
      out.write("</TD>\r\n");
      out.write("<TD ALIGN=CENTER> <A HREF=cal1.jsp?date=next> next </A>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("<!-- the main table -->\r\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=lightblue BORDER=1 CELLPADDING=10>\r\n");
      out.write("<TR>\r\n");
      out.write("<TH> Time </TH>\r\n");
      out.write("<TH> Appointment </TH>\r\n");
      out.write("</TR>\r\n");
      out.write("<FORM METHOD=POST ACTION=cal1.jsp>\r\n");

    for(int i=0; i<table.getEntries().getRows(); i++) {
       cal.Entry entr = table.getEntries().getEntry(i);

      out.write("\r\n");
      out.write("    <TR>\r\n");
      out.write("    <TD>\r\n");
      out.write("    <A HREF=cal2.jsp?time=");
      out.print( entr.getHour() );
      out.write(">\r\n");
      out.write("        ");
      out.print( entr.getHour() );
      out.write(" </A>\r\n");
      out.write("    </TD>\r\n");
      out.write("    <TD BGCOLOR=");
      out.print( entr.getColor() );
      out.write(">\r\n");
      out.write("    ");
 out.print(util.HTMLFilter.filter(entr.getDescription())); 
      out.write("\r\n");
      out.write("    </TD>\r\n");
      out.write("    </TR>\r\n");

    }

      out.write("\r\n");
      out.write("</FORM>\r\n");
      out.write("</TABLE>\r\n");
      out.write("<BR>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<TABLE WIDTH=60% BGCOLOR=yellow CELLPADDING=15>\r\n");
      out.write("<TR>\r\n");
      out.write("<TD ALIGN=CENTER>  ");
 out.print(util.HTMLFilter.filter(table.getName())); 
      out.write(" :\r\n");
      out.write("             ");
 out.print(util.HTMLFilter.filter(table.getEmail())); 
      out.write(" </TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</CENTER>\r\n");
      out.write("\r\n");

    } else {

      out.write("\r\n");
      out.write("<font size=5>\r\n");
      out.write("    You must enter your name and email address correctly.\r\n");
      out.write("</font>\r\n");

    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
