/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2017-05-25 01:43:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.simpletag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class foo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/example-taglib.tld", Long.valueOf(1427091246000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feg_005flog;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1 = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005feg_005flog = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1.release();
    _005fjspx_005ftagPool_005feg_005flog.release();
    _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Radio stations that rock:\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      //  eg:foo
      examples.FooTag _jspx_th_eg_005ffoo_005f0 = (examples.FooTag) _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1.get(examples.FooTag.class);
      _jspx_th_eg_005ffoo_005f0.setPageContext(_jspx_page_context);
      _jspx_th_eg_005ffoo_005f0.setParent(null);
      // /jsp/simpletag/foo.jsp(24,0) name = att1 type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_eg_005ffoo_005f0.setAtt1("98.5");
      // /jsp/simpletag/foo.jsp(24,0) name = att2 type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_eg_005ffoo_005f0.setAtt2("92.3");
      // /jsp/simpletag/foo.jsp(24,0) name = att3 type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_eg_005ffoo_005f0.setAtt3("107.7");
      int _jspx_eval_eg_005ffoo_005f0 = _jspx_th_eg_005ffoo_005f0.doStartTag();
      if (_jspx_eval_eg_005ffoo_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        String member = null;
        if (_jspx_eval_eg_005ffoo_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_eg_005ffoo_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_eg_005ffoo_005f0.doInitBody();
        }
        member = (String) _jspx_page_context.findAttribute("member");
        do {
          out.write("\r\n");
          out.write("<li>");
          out.print( member );
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_eg_005ffoo_005f0.doAfterBody();
          member = (String) _jspx_page_context.findAttribute("member");
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_eg_005ffoo_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_eg_005ffoo_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1.reuse(_jspx_th_eg_005ffoo_005f0);
        return;
      }
      _005fjspx_005ftagPool_005feg_005ffoo_0026_005fatt3_005fatt2_005fatt1.reuse(_jspx_th_eg_005ffoo_005f0);
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      if (_jspx_meth_eg_005flog_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_eg_005flog_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_eg_005flog_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eg:log
    examples.LogTag _jspx_th_eg_005flog_005f0 = (examples.LogTag) _005fjspx_005ftagPool_005feg_005flog.get(examples.LogTag.class);
    _jspx_th_eg_005flog_005f0.setPageContext(_jspx_page_context);
    _jspx_th_eg_005flog_005f0.setParent(null);
    int _jspx_eval_eg_005flog_005f0 = _jspx_th_eg_005flog_005f0.doStartTag();
    if (_jspx_eval_eg_005flog_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_eg_005flog_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_eg_005flog_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_eg_005flog_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("Did you see me on the stderr window?\r\n");
        int evalDoAfterBody = _jspx_th_eg_005flog_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_eg_005flog_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_eg_005flog_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feg_005flog.reuse(_jspx_th_eg_005flog_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005feg_005flog.reuse(_jspx_th_eg_005flog_005f0);
    return false;
  }

  private boolean _jspx_meth_eg_005flog_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  eg:log
    examples.LogTag _jspx_th_eg_005flog_005f1 = (examples.LogTag) _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser.get(examples.LogTag.class);
    _jspx_th_eg_005flog_005f1.setPageContext(_jspx_page_context);
    _jspx_th_eg_005flog_005f1.setParent(null);
    // /jsp/simpletag/foo.jsp(33,0) name = toBrowser type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_eg_005flog_005f1.setToBrowser("true");
    int _jspx_eval_eg_005flog_005f1 = _jspx_th_eg_005flog_005f1.doStartTag();
    if (_jspx_eval_eg_005flog_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_eg_005flog_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_eg_005flog_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_eg_005flog_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("Did you see me on the browser window as well?\r\n");
        int evalDoAfterBody = _jspx_th_eg_005flog_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_eg_005flog_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_eg_005flog_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser.reuse(_jspx_th_eg_005flog_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005feg_005flog_0026_005ftoBrowser.reuse(_jspx_th_eg_005flog_005f1);
    return false;
  }
}
